insert into tblBook (book_id, course_id, book_name, book_type, stock) values (1, 1, 'Quantum Leap: A Beginner''s Guide to the Microcosmos', 'phyiscal book', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (2, 2, 'Data Deluge: Navigating the Digital Ocean', 'phyiscal book', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (3, 3, 'Brushstrokes of Genius: Unveiling the Renaissance', 'ebook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (4, 4, 'Trade Winds: Navigating the Global Economy', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (5, 5, 'Green Horizons: Mapping Sustainable Futures', 'ebook', 10);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (6, 6, 'Inkspiration: Igniting Your Creative Spark', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (7, 7, 'Mind Matters: Decoding the Brain''s Secrets', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (8, 8, 'Echoes of Antiquity: Unraveling Myth from History', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (9, 9, 'Startup Savvy: A Guide to Entrepreneurial Success', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (10, 10, 'Ideas in Action: Navigating Modern Politics', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (11, 11, 'Bodies in Balance: Understanding Human Anatomy', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (12, 12, 'Digital Dynamo: Mastering Marketing in the Digital Age', 'ebook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (13, 13, 'Stargazer''s Guide: Journey Through the Cosmos', 'audiobook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (14, 14, 'Sacred Stories: Exploring the World''s Religions', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (15, 15, 'Speak with Impact: Mastering the Art of Public Speaking', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (16, 16, 'Digital Fortress: Navigating Cybersecurity Challenges', 'audiobook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (17, 17, 'Breaking Boundaries: Exploring Gender and Society', 'audiobook', 10);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (18, 18, 'Money Matters: Navigating Financial Landscapes', 'ebook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (19, 19, 'Literary Landscapes: Exploring Contemporary Voices', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (20, 20, 'Robot Revolution: Exploring the World of Robotics', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (21, 21, 'Chemistry Chronicles: Exploring Organic Matter', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (22, 22, 'Soulful Sounds: Tracing the History of Jazz and Blues', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (23, 23, 'Language Lens: Exploring the World of Linguistics', 'ebook', 10);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (24, 24, 'Cityscapes: Navigating Urban Development', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (25, 25, 'Social Synchrony: Exploring Human Behavior', 'ebook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (26, 26, 'Game Changer: Mastering the Art of Game Design', 'ebook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (27, 27, 'Philosophical Ponderings: Exploring Life''s Big Questions', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (28, 28, 'Economic Insights: Navigating Microeconomic Principles', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (29, 29, 'Cinematic Chronicles: Exploring the World of Film', 'ebook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (30, 30, 'Ethical Algorithms: Navigating AI in Society', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (31, 31, 'Wellness Wisdom: Navigating Health and Wellness', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (32, 32, 'Genetic Genesis: Exploring the Code of Life', 'audiobook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (33, 33, 'Ancient Artifacts: Exploring Archaeological Wonders', 'phyiscal book', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (34, 34, 'Green Designs: Navigating Sustainable Architecture', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (35, 35, 'Global Dynamics: Navigating International Relations', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (36, 36, 'Code Chronicles: Navigating the World of Programming', 'audiobook', 10);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (37, 37, 'Rights Reckoning: Exploring Human Rights and Justice', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (38, 38, 'Mind Matters: Exploring Cognitive Psychology', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (39, 39, 'Energy Evolution: Navigating Sustainable Energy Solutions', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (40, 40, 'Harmony Handbook: Exploring Music Theory', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (41, 41, 'Data Dynamics: Navigating the World of Big Data', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (42, 42, 'Political Perspectives: Exploring Comparative Politics', 'ebook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (43, 43, 'Stargazer''s Handbook: Navigating the Cosmos', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (44, 44, 'Fashion Forward: Exploring the World of Design', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (45, 45, 'Peaceful Pathways: Navigating Conflict Resolution', 'ebook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (46, 46, 'Cultural Chronicles: Exploring Anthropological Wonders', 'ebook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (47, 47, 'Economic Epochs: Navigating Macroeconomic Theories', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (48, 48, 'People Power: Navigating Human Resources', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (49, 49, 'Visual Visions: Exploring Digital Design', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (50, 50, 'Deviant Dynamics: Exploring Sociological Perspectives', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (51, 1, 'Quantum Quandaries: Exploring the Mysteries of the Subatomic World', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (52, 2, 'Data Dives: Deep Exploration into Data Science', 'phyiscal book', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (53, 3, 'Renaissance Revelations: Unraveling Artistic Masterpieces', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (54, 4, 'Trade Talks: Navigating Global Economic Frontiers', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (55, 5, 'Eco-Essentials: Essential Reads on Environmental Sustainability', 'phyiscal book', 3);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (56, 6, 'The Writer''s Journey: Mastering Creative Expression', 'audiobook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (57, 7, 'Brain Bytes: Understanding the Neurological Wonders', 'ebook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (58, 8, 'Mythical Explorations: Journeys into Ancient Civilizations', 'phyiscal book', 10);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (59, 9, 'Startup Secrets: Insider Strategies for Entrepreneurial Success', 'ebook', 10);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (60, 10, 'Political Paradigms: Perspectives on Modern Governance', 'audiobook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (61, 11, 'Bodily Explorations: Insights into Human Anatomy', 'ebook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (62, 12, 'Digital Dynamics: Navigating Marketing in the Digital Era', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (63, 13, 'Cosmic Chronicles: Exploring the Depths of the Universe', 'audiobook', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (64, 14, 'Cultural Crossroads: Understanding World Religions', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (65, 15, 'Speak Up: Essential Guide to Public Speaking', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (66, 16, 'Cyber Savvy: Mastering Cybersecurity Essentials', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (67, 17, 'Gender Dynamics: Perspectives on Identity and Society', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (68, 18, 'Financial Frontiers: Navigating the World of Finance', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (69, 19, 'Contemporary Chronicles: Exploring Modern Literature', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (70, 20, 'Robot Revolution: Engineering the Future', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (71, 21, 'Chemistry Chronicles: Adventures in Organic Chemistry', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (72, 22, 'Jazz Journeys: Tracing the Evolution of Music', 'phyiscal book', 10);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (73, 23, 'Linguistic Landscapes: Exploring Language Diversity', 'ebook', 4);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (74, 24, 'Urban Utopias: Planning Cities for the Future', 'audiobook', 1);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (75, 25, 'Social Synapses: Insights into Human Behavior', 'phyiscal book', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (76, 26, 'Game Guru: Strategies for Game Design Excellence', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (77, 27, 'Philosophical Pathways: Navigating Life''s Big Questions', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (78, 28, 'Micro Matters: Insights into Economic Principles', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (79, 29, 'Cinematic Chronicles: Journey into Film History', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (80, 30, 'Ethical Engines: Navigating AI Ethics', 'ebook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (81, 31, 'Wellness Wisdom: Navigating Health and Well-being', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (82, 32, 'Genetic Journeys: Adventures in DNA', 'phyiscal book', 10);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (83, 33, 'Archaeological Adventures: Unearthing Ancient Worlds', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (84, 34, 'Sustainable Structures: Innovations in Architecture', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (85, 35, 'Global Dynamics: Navigating International Relations', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (86, 36, 'Coding Chronicles: Mastering Programming Concepts', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (87, 37, 'Human Rights Handbook: Insights into Social Justice', 'ebook', 10);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (88, 38, 'Mind Matters: Understanding Cognitive Psychology', 'phyiscal book', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (89, 39, 'Energy Explorations: Navigating Sustainable Technologies', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (90, 40, 'Melodies and Meanings: Exploring Music Theory', 'ebook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (91, 41, 'Data Discoveries: Navigating Big Data Analytics', 'ebook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (92, 42, 'Political Perspectives: Comparative Politics Unveiled', 'audiobook', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (93, 43, 'Stellar Explorations: Journey into Astronomy', 'phyiscal book', 11);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (94, 44, 'Fashion Forward: Designing the Future', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (95, 45, 'Pathways to Peace: Navigating Conflict Resolution', 'audiobook', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (96, 46, 'Anthropological Adventures: Exploring Human Cultures', 'phyiscal book', 8);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (97, 47, 'Macroeconomic Musings: Insights into Economic Policies', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (98, 48, 'People Power: Mastering Human Resource Management', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (99, 49, 'Visual Voyages: Adventures in Graphic Design', 'phyiscal book', 9);
insert into tblBook (book_id, course_id, book_name, book_type, stock) values (100, 50, 'Sociological Surveys: Insights into Deviance and Crime', 'phyiscal book', 8);