insert into tblCourse (course_id, course_name, course_leader) values (0, 'NonCourseSpecificStaff', 'Staff');
insert into tblCourse (course_id, course_name, course_leader) values (1, 'Quantum Mechanics for Beginners', 'Sheilakathryn McKiddin');
insert into tblCourse (course_id, course_name, course_leader) values (2, 'Introduction to Data Science', 'Eal Trafford');
insert into tblCourse (course_id, course_name, course_leader) values (3, 'Renaissance Art History', 'Tammy Stribling');
insert into tblCourse (course_id, course_name, course_leader) values (4, 'Global Economics and Trade', 'York Tierney');
insert into tblCourse (course_id, course_name, course_leader) values (5, 'Environmental Sustainability Studies', 'Irvin Husband');
insert into tblCourse (course_id, course_name, course_leader) values (6, 'Creative Writing Workshop', 'Konstanze Halt');
insert into tblCourse (course_id, course_name, course_leader) values (7, 'Neurobiology and Behavior', 'Alberik French');
insert into tblCourse (course_id, course_name, course_leader) values (8, 'Ancient Civilizations: Myth and Reality', 'Susanna Ughetti');
insert into tblCourse (course_id, course_name, course_leader) values (9, 'Entrepreneurship Fundamentals', 'Aline Millgate');
insert into tblCourse (course_id, course_name, course_leader) values (10, 'Modern Political Theory', 'Jodi Chisholm');
insert into tblCourse (course_id, course_name, course_leader) values (11, 'Human Anatomy and Physiology', 'Teriann Mowle');
insert into tblCourse (course_id, course_name, course_leader) values (12, 'Digital Marketing Strategies', 'Mathew Cameli');
insert into tblCourse (course_id, course_name, course_leader) values (13, 'Astrophysics: Exploring the Universe', 'Pavia Beardshall');
insert into tblCourse (course_id, course_name, course_leader) values (14, 'World Religions and Cultures', 'Gun Thaw');
insert into tblCourse (course_id, course_name, course_leader) values (15, 'Public Speaking Mastery', 'Lee Divine');
insert into tblCourse (course_id, course_name, course_leader) values (16, 'Cybersecurity Fundamentals', 'Desmund Cabell');
insert into tblCourse (course_id, course_name, course_leader) values (17, 'Gender Studies: Identity and Society', 'Brook Giacomazzo');
insert into tblCourse (course_id, course_name, course_leader) values (18, 'Financial Management Principles', 'Tracey Kirkbride');
insert into tblCourse (course_id, course_name, course_leader) values (19, 'Contemporary Literature', 'Blancha Eckersley');
insert into tblCourse (course_id, course_name, course_leader) values (20, 'Introduction to Robotics', 'Daveen Yurocjkin');
insert into tblCourse (course_id, course_name, course_leader) values (21, 'Organic Chemistry Laboratory', 'Allyson Double');
insert into tblCourse (course_id, course_name, course_leader) values (22, 'History of Jazz and Blues', 'Harper Corbert');
insert into tblCourse (course_id, course_name, course_leader) values (23, 'Introduction to Linguistics', 'Joletta Beaston');
insert into tblCourse (course_id, course_name, course_leader) values (24, 'Urban Planning and Development', 'Tallulah Crawforth');
insert into tblCourse (course_id, course_name, course_leader) values (25, 'Social Psychology: Understanding Behavior', 'Ddene Perot');
insert into tblCourse (course_id, course_name, course_leader) values (26, 'Game Design Fundamentals', 'Caroljean Lagde');
insert into tblCourse (course_id, course_name, course_leader) values (27, 'Introduction to Philosophy', 'Maryjo Kilner');
insert into tblCourse (course_id, course_name, course_leader) values (28, 'Microeconomics: Markets and Consumers', 'Mella Le Noire');
insert into tblCourse (course_id, course_name, course_leader) values (29, 'Introduction to Film Studies', 'Erastus Waddy');
insert into tblCourse (course_id, course_name, course_leader) values (30, 'Artificial Intelligence Ethics', 'Melita Fetherston');
insert into tblCourse (course_id, course_name, course_leader) values (31, 'Health and Wellness Management', 'Becky Sandars');
insert into tblCourse (course_id, course_name, course_leader) values (32, 'Genetics and Genetic Engineering', 'Frasquito Tapin');
insert into tblCourse (course_id, course_name, course_leader) values (33, 'Archaeology: Unearthing the Past', 'Alasteir Ledgard');
insert into tblCourse (course_id, course_name, course_leader) values (34, 'Sustainable Architecture and Design', 'Elwira Cuss');
insert into tblCourse (course_id, course_name, course_leader) values (35, 'International Relations in the 21st Century', 'Gracie Bolt');
insert into tblCourse (course_id, course_name, course_leader) values (36, 'Introduction to Computer Programming', 'Silvie Sennett');
insert into tblCourse (course_id, course_name, course_leader) values (37, 'Human Rights and Social Justice', 'Joane Fetherstan');
insert into tblCourse (course_id, course_name, course_leader) values (38, 'Cognitive Psychology: Mind and Behavior', 'Zulema Richings');
insert into tblCourse (course_id, course_name, course_leader) values (39, 'Sustainable Energy Technologies', 'Nelle Betteson');
insert into tblCourse (course_id, course_name, course_leader) values (40, 'Music Theory and Composition', 'Joby Denyukhin');
insert into tblCourse (course_id, course_name, course_leader) values (41, 'Introduction to Big Data Analytics', 'Babb Fratson');
insert into tblCourse (course_id, course_name, course_leader) values (42, 'Comparative Politics', 'Tobe Crenshaw');
insert into tblCourse (course_id, course_name, course_leader) values (43, 'Introduction to Astronomy', 'Ardyth Fyers');
insert into tblCourse (course_id, course_name, course_leader) values (44, 'Fashion Design Fundamentals', 'Sileas Duckitt');
insert into tblCourse (course_id, course_name, course_leader) values (45, 'Conflict Resolution and Mediation', 'Rupert Hankins');
insert into tblCourse (course_id, course_name, course_leader) values (46, 'Introduction to Cultural Anthropology', 'Elysee Koubek');
insert into tblCourse (course_id, course_name, course_leader) values (47, 'Macroeconomics: Policy and Theory', 'Christal Gillet');
insert into tblCourse (course_id, course_name, course_leader) values (48, 'Introduction to Human Resource Management', 'Cull Dinsey');
insert into tblCourse (course_id, course_name, course_leader) values (49, 'Digital Illustration and Graphic Design', 'Maribelle Bushell');
insert into tblCourse (course_id, course_name, course_leader) values (50, 'Sociology of Deviance and Crime', 'Datha Legrand');
